# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import movsearch_pb2 as movsearch__pb2


class SearchMovieStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.search = channel.unary_unary(
        '/movsearch.SearchMovie/search',
        request_serializer=movsearch__pb2.Query.SerializeToString,
        response_deserializer=movsearch__pb2.Result.FromString,
        )


class SearchMovieServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchMovieServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'search': grpc.unary_unary_rpc_method_handler(
          servicer.search,
          request_deserializer=movsearch__pb2.Query.FromString,
          response_serializer=movsearch__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'movsearch.SearchMovie', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class SearchSoundStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.search = channel.unary_unary(
        '/movsearch.SearchSound/search',
        request_serializer=movsearch__pb2.Query.SerializeToString,
        response_deserializer=movsearch__pb2.Result.FromString,
        )


class SearchSoundServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def search(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SearchSoundServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'search': grpc.unary_unary_rpc_method_handler(
          servicer.search,
          request_deserializer=movsearch__pb2.Query.FromString,
          response_serializer=movsearch__pb2.Result.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'movsearch.SearchSound', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
